# Input configuration file

base:
  random_state: 42
  log_level: INFO

data_load:
  input_path: "data/raw/"
  input_name: "sex_data.csv"
  target: "label"
  output_path: "data/curated/"
  output_name: "data.csv"

data_split:
  test_size: 0.15
  val_size: 0.1
  output_path: 'data/curated/'
  output_name_train: 'train.csv'
  output_name_test: 'test.csv'
  output_name_val: 'val.csv'

data:
  train_path: "data/curated/"
  test_path: "data/curated/"
  train_file: "train.csv"
  test_file: "test.csv"

model:
  n_neurons: 64
  dropout: 0.25
  max_len: 20
  output_dir: "models"

training:
  weight_decay: 0.005
  batch_size: 64
  epochs: 10
  initial_learning_rate: 0.01
  decay_rate: 0.1
  early_stopping_delta: 0.01
  early_stopping_patience: 5

evaluate:
  reports_dir: reports
  metrics_file: 'metrics.json'
  confusion_matrix_image: 'confusion_matrix.png'
  roc_curve_image: 'roc_curve.png'
  pr_curve_image: 'pr_curve.png'
  ks_curve_image: 'ks_curve.png'
  gains_curve_image: 'gains_curve.png'
  lift_curve_image: 'lift_curve.png'
  calibration_curve_image: 'calibration_curve.png'